export const SETTINGS_DEFAULT_VALUES: Record<string, boolean | number | string> = {
  'account.profile.profileVisibility': true,
  'account.profile.digestLanguage': 'es',
  'account.profile.defaultLanding': 'enterpriseDashboard',
  'account.profile.defaultLandingSite': '',
  'account.privacy.auditTrail': true,
  'account.privacy.sessionTimeout': '30',
  'notifications.alerts.criticalIncidents': true,
  'notifications.alerts.visitorArrivals': true,
  'notifications.channels.channelEmail': true,
  'notifications.channels.channelSms': false,
  'notifications.channels.channelPush': true,
  'security.auth.mfa': true,
  'security.auth.passwordRotation': '60',
  'security.sessions.sessionLimit': 3,
  'security.sessions.geoLock': false,
  'appearance.generalLook.themeMode': 'auto',
  'appearance.generalLook.themePreference': 'system',
  'appearance.generalLook.density': 'standard',
  'appearance.topbar.topbarBlur': 14,
  'appearance.topbar.topbarBadges': true,
  'appearance.topbar.topbarPatternEnabled': true,
  'appearance.topbar.topbarPatternKind': 'subtle-diagonal',
  'appearance.topbar.topbarPatternOpacity': 0.08,
  'appearance.topbar.topbarPatternScale': 28,
  'appearance.charts.chartPalette': 'brand',
  'appearance.charts.chartAnimation': true,
}
